A2008212272-SLN/PaqueteTuristico.MVC/Controllers/HospedajesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaquetesTuristicos.Entities;
using PaquetesTuristicos.Persistence;
using PaquetesTuristicos.Entities.IRepositories;

namespace PaqueteTuristico.MVC.Controllers
{
    public class HospedajesController : Controller
    {
        // private PaqueteTuristicoDbContext db = new PaqueteTuristicoDbContext();
        private readonly IUnityofWork _UnityOfWork;

        public HospedajesController(IUnityofWork unityOfWork)
        {
            _UnityOfWork = unityOfWork;
        }

        public HospedajesController()
        {

        }
        // GET: Hospedajes
        public ActionResult Index()
        {
            //   return View(db.ServicioTuristicoes.ToList());
            return View(_UnityOfWork.Hospedaje.GetAll());

        }

        // GET: Hospedajes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Hospedaje hospedaje = db.ServicioTuristicoes.Find(id);
            Hospedaje hospedaje = _UnityOfWork.Hospedaje.Get(id);

            if (hospedaje == null)
            {
                return HttpNotFound();
            }
            return View(hospedaje);
        }

        // GET: Hospedajes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospedajes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServicioTuristicoId,Fecha,Hora,Direccion,Descripcion,TipoHospedaje,CalificacionHospedaje,CategoriaHospedaje,ServicioHospedaje")] Hospedaje hospedaje)
        {
            if (ModelState.IsValid)
            {
                // db.ServicioTuristicoes.Add(hospedaje);
                _UnityOfWork.Hospedaje.Add(hospedaje);
                // db.SaveChanges();
                _UnityOfWork.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(hospedaje);
        }

        // GET: Hospedajes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //  Hospedaje hospedaje = db.ServicioTuristicoes.Find(id);
            Hospedaje hospedaje = _UnityOfWork.Hospedaje.Get(id);
            if (hospedaje == null)
            {
                return HttpNotFound();
            }
            return View(hospedaje);
        }

        // POST: Hospedajes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServicioTuristicoId,Fecha,Hora,Direccion,Descripcion,TipoHospedaje,CalificacionHospedaje,CategoriaHospedaje,ServicioHospedaje")] Hospedaje hospedaje)
        {
            if (ModelState.IsValid)
            {
                //  db.Entry(hospedaje).State = EntityState.Modified;
                _UnityOfWork.StateModified(hospedaje);

                //  db.SaveChanges();
                _UnityOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(hospedaje);
        }

        // GET: Hospedajes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Hospedaje hospedaje = db.ServicioTuristicoes.Find(id);
            Hospedaje hospedaje = _UnityOfWork.Hospedaje.Get(id);
            if (hospedaje == null)
            {
                return HttpNotFound();
            }
            return View(hospedaje);
        }

        // POST: Hospedajes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //  Hospedaje hospedaje = db.ServicioTuristicoes.Find(id);
            Hospedaje hospedaje = _UnityOfWork.Hospedaje.Get(id);

            // db.ServicioTuristicoes.Remove(hospedaje);
            _UnityOfWork.Hospedaje.Delete(hospedaje);

            //  db.SaveChanges();
            _UnityOfWork.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
                _UnityOfWork.Dispose();

            }
            base.Dispose(disposing);
        }
    }
}

A2008212272-SLN/PaqueteTuristico.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LC-3 Y 4  ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Paquete turistico", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Alimentaciones", "Index", "Alimentaciones")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                    <li>@Html.ActionLink("ComprobantesPago", "Index", "ComprobantesPago")</li>
                    <li>@Html.ActionLink("Empleados", "Index", "Empleados")</li>
                    <li>@Html.ActionLink("Hospedaje", "Index", "Hospedajes")</li>
                    <li>@Html.ActionLink("Paquetes", "Index", "Paquetes")</li>
                    <li>@Html.ActionLink("Transportes", "Index", "Transportes")</li>
                    <li>@Html.ActionLink("VentaPaquetes", "Index", "VentaPaquetes")</li>
                    
                   
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tenorio Sulca Edison</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>